version: "3.8"

services:
    database:
        build:
            context: database
            dockerfile: Dockerfile
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
        depends_on:
            - database
    
    otto-scraper:
        build:
            context: scraping/otto_de
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - database
        ports:
            - 9080:9080
        command: [ "./wait-for-it.sh", "database:5432",  "--", "scrapyrt", "-i", "0.0.0.0"]
    
    basic-evaluation-webapp:
        build:
            context: analysis/basic-evaluation
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8501:8501
        depends_on: 
            - database

    scraping-admin:
        build:
            context: scraping/scraping-admin
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8502:8501
        depends_on: 
            - database